# Generated by Django 4.0.3 on 2022-04-20 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Ip_address',
            field=models.GenericIPAddressField(),
        ),
    ]
