# Generated by Django 4.0.3 on 2022-04-20 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_address_ip_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Email',
            field=models.EmailField(max_length=120),
        ),
    ]
