# Generated by Django 4.0.3 on 2022-04-20 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_alter_address_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='income',
            field=models.PositiveIntegerField(),
        ),
    ]
