# Generated by Django 4.0.3 on 2022-04-20 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_address_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Name',
            field=models.CharField(max_length=120),
        ),
    ]
